PokemonBundle\Entity\Pokemon:
    type: entity
    table: pokemon
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        types:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        stamina:
            type: integer
            nullable: false
            options:
                unsigned: false
        attack:
            type: integer
            nullable: false
            options:
                unsigned: false
        defense:
            type: integer
            nullable: false
            options:
                unsigned: false
        captureRate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: capture_rate
        fleeRate:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: flee_rate
        candy:
            type: integer
            nullable: true
            options:
                unsigned: false
        quickMoves:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: quick_moves
        specialMoves:
            type: string
            nullable: true
            length: 150
            options:
                fixed: false
            column: special_moves
    manyToMany:
        type:
            targetEntity: Type
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: pokemon
            joinTable:
                name: pokemon_type
                joinColumns:
                    -
                        name: pokemon_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: type_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
